DROP TABLE IF EXISTS stores;
DROP TABLE IF EXISTS forms CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS device_locations CASCADE;
DROP TABLE IF EXISTS form_def CASCADE;
DROP TABLE IF EXISTS form_type CASCADE;
DROP TABLE IF EXISTS form_data CASCADE;
DROP TABLE IF EXISTS form_field CASCADE;
