DROP TABLE IF EXISTS stores;
DROP TABLE IF EXISTS forms CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS device_location CASCADE;
DROP TABLE IF EXISTS form_field CASCADE;
DROP TABLE IF EXISTS form_type CASCADE;
DROP TABLE IF EXISTS form_data CASCADE;
DROP TYPE IF EXISTS form_type;