FROM nginx:alpine

RUN apk add --update nodejs

RUN mkdir -p /web
COPY . /web
RUN rm -rf /web/node_modules/
WORKDIR /web
RUN npm install
RUN npm run build:dev

COPY ./nginx-config/default.conf /etc/nginx/conf.d/default.conf
COPY ./public/ /usr/share/nginx/html
